name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          aws-region: us-east-1  # replace with your region

      # 3. Debug - list repo root files
      - name: List repo root files
        run: ls -lh $GITHUB_WORKSPACE

      # 4. Sync only HTML, CSS, JS, images to S3 bucket root
      - name: Sync site files to S3
        run: |
          aws s3 sync $GITHUB_WORKSPACE s3://cryptopulse-site/ --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "README.md" \
            --exclude "*.md" \
            --include "*.html" \
            --include "*.css" \
            --include "*.js" \
            --include "*.png" \
            --include "*.jpg" \
            --include "*.jpeg" \
            --include "*.gif"
          
          echo "S3 bucket contents after sync:"
          aws s3 ls s3://cryptopulse-site/

      # 5. Confirm docs.html exists in S3
      - name: Check if docs.html exists
        run: |
          if aws s3 ls s3://cryptopulse-site/docs.html; then
            echo "docs.html successfully uploaded!"
          else
            echo "ERROR: docs.html not found in S3!"
            exit 1
          fi

      # 6. Invalidate CloudFront cache
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CF_DIST_ID }} \
            --paths "/*"
